### ISSUE TITLE
There is no way to have any padding/margin between items. How to style items?

### ISSUE THREAD

**Issue by prateekchachra** [kalontech/ReactNativeWheelPicker#101]
I wanted some spacing to have the styling more proper in the wheel picker, unfortunately it's all very packed together. And increasing the text size just makes it look worse.

Any suggestions? I tried to use the 'itemStyle' from the <Picker> documentation but to no avail.

**Comment by ArtemKosiakevych** [comment]
What platform?

**Comment by ArtemKosiakevych** [comment]
You can use `itemStyle` for IOS but for android, there is no way to set item styling yet

**Comment by edikamy** [comment]
Still no way?

**Comment by pupubird** [comment]
Still no way? +1
