### ISSUE TITLE
Cannot fix link issue in Expo

### ISSUE THREAD

**Issue by smlarkin** [kalontech/ReactNativeWheelPicker#106]
Hello, I asked for help here:

https://github.com/KalonTech/ReactNativeWheelPicker/issues/83

But I think this issue cannot be fixed in Expo.

I get the same error message:

I am getting this error for a package in Android:

"Invariant Violation: requireNativeComponent: "WheelPicker" was not found in the UIManager."

What can you do to fix this in Expo?

**Comment by ArtemKosiakevych** [comment]
Read #83
