### ISSUE TITLE
inside content not centered

### ISSUE THREAD

**Issue by TQCasey** [kalontech/ReactNativeWheelPicker#111]
the inside content not centered in the wiget

**Comment by yestay90** [comment]
Hello @TQCasey. Did you solve this problem?

**Comment by TQCasey** [comment]
@yestay90 Yes，I forked another one , try this https://github.com/TQCasey/ReactNativeWheelPicker.git ,It's stable

**Comment by ArtemKosiakevych** [comment]
fixed
