### ISSUE TITLE
Is there any ways to use it with Expo? I tried But it Fails!

### ISSUE THREAD

**Issue by aadarshvelu** [kalontech/ReactNativeWheelPicker#128]
Hi, This Picker is cool, So I'm beginner so I preferred using Expo, I saw your project on NPM Manager,
So Is there any ways to integrate with expo? I tried using yarn add, and successfully Installed... using this command : react-native link react-native-wheel-picker-android and this also done. 

But It isn't working!

CODE : 

`import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import { WheelPicker } from "react-native-wheel-picker-android";

export default function App() {
#
   const days = ["Select The Day!"], month = ["Select The Month!"];
    
    for (let i = 1;i <= 31;i++) {
        days.push(i+"");
    }

    for (let j = 1;j <= 12;j++) {
        month.push(j+"")
    }

    const handleOnPress = () => {
      alert("Trapped!")
    }

  return (
    <React.Fragment>
      <View style={styles.container}>
        <View>
            <Button title={"Select Country"} onPress={handleOnPress} />
        </View>
        <View style={{flex: 1, flexDirection: "row"}}>
            <WheelPicker isCyclic={true} data={days} />
            <WheelPicker data={month} />
        </View>
      </View>
    </React.Fragment>
  );

}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
`

But I Encountered with this error : 

`requireNativeComponent: "WheelPicker" was not found in the UIManager.

Stack trace:
  node_modules\react-native\Libraries\ReactNative\getNativeComponentAttributes.js:30:4 in getNativeComponentAttributes
  node_modules\react-native\Libraries\Renderer\shims\ReactNativeViewConfigRegistry.js:102:25 in exports.get
  node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:4097:40 in createInstance
  node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15835:12 in completeWork
  node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19409:28 in completeUnitOfWork
  node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19380:30 in performUnitOfWork
  node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19347:39 in workLoopSync
  node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18997:22 in renderRoot
  [native code]:null in renderRoot
  node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18709:28 in runRootCallback
  [native code]:null in runRootCallback
  node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5642:32 in runWithPriority$argument_1
  node_modules\scheduler\cjs\scheduler.development.js:643:23 in unstable_runWithPriority
  node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5638:22 in flushSyncCallbackQueueImpl
  node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5627:28 in flushSyncCallbackQueue
  node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18556:30 in scheduleUpdateOnFiber
  node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:21822:15 in scheduleRootUpdate
  node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:23042:20 in ReactNativeRenderer.render
  node_modules\react-native\Libraries\ReactNative\renderApplication.js:52:52 in renderApplication
  node_modules\react-native\Libraries\ReactNative\AppRegistry.js:116:10 in runnables.appKey.run
  node_modules\react-native\Libraries\ReactNative\AppRegistry.js:197:26 in runApplication
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:436:47 in __callFunction
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:111:26 in __guard$argument_0
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10 in __guard
  node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:110:17 in __guard$argument_0
  [native code]:null in callFunctionReturnFlushedQueue
  ...`

**Comment by zeritte** [comment]
since this needs to be linked, it cant be used with expo managed flow. you need to eject first

**Comment by aadarshvelu** [comment]
> since this needs to be linked, it cant be used with expo managed flow. you need to eject first

Thanks!
