### ISSUE TITLE
inside ScrollView

### ISSUE THREAD

**Issue by VBarzionov** [kalontech/ReactNativeWheelPicker#79]
Android version does not correctly work inside vertical ScrollView.

**Comment by fjobeir** [comment]
+1

**Comment by fjobeir** [comment]
I have the same issue, could you solve it @VBarzionov, please?

**Comment by VBarzionov** [comment]
> I have the same issue, could you solve it @VBarzionov, please?

I have not, I switched to react-native-wheel-picker.

**Comment by fjobeir** [comment]
I did the same
https://github.com/TronNatthakorn/react-native-wheel-pick

wish you a very good luck

**Comment by PetrVasilev** [comment]
The same with me

**Comment by saravanabalagi** [comment]
If you can't wait you can use my [library](https://github.com/saravanabalagi/react-native-wheel-picker-simple). Thanks to [react-native-wheel/issues/3](https://github.com/shexiaoheng/react-native-wheel/issues/3), I was able to quickly solve it.

**Comment by saravanabalagi** [comment]
If you can't wait you can use my [library](https://github.com/saravanabalagi/react-native-wheel-picker-simple). Thanks to this [issue](https://github.com/shexiaoheng/react-native-wheel/issues/3) from another lib, I was able to quickly solve it.
