### ISSUE TITLE
`onItemSelected` method auto trigger in Android

### ISSUE THREAD

**Issue by somebugs** [kalontech/ReactNativeWheelPicker#81]
`onItemSelected` method auto trigger in Android, so I can not set an initial value, It is always return 0

**Comment by santiagomartinez** [comment]
I'm having the same problem. When the component mounts, it triggers the method with value 0.

**Comment by madandrija** [comment]
> I'm having the same problem. When the component mounts, it triggers the method with value 0.

Same issue here

**Comment by santiagomartinez** [comment]
I ended up forking from 871da247b7c8b3ae9328264a453de54b889fa4e8

**Comment by madandrija** [comment]
> I ended up forking from [871da24](https://github.com/KalonTech/ReactNativeWheelPicker/commit/871da247b7c8b3ae9328264a453de54b889fa4e8)

I can't seem to find your fork, do you have a link?

**Comment by santiagomartinez** [comment]
Sorry but it's a private fork. I didn't need to change anything from that commit, so it is good enough for you to use the commit ID in your `package.json` file.

**Comment by madandrija** [comment]
Using initPosition seems to solve the issue

**Comment by cotrim149** [comment]
> Using initPosition seems to solve the issue

Yes, this solve the problem.
