### ISSUE TITLE
Why Invariant Violation：Invariant Violation：requireNativeComponent：“wheelPicker” was not found in the UIManager。

### ISSUE THREAD

**Issue by KenPanda** [kalontech/ReactNativeWheelPicker#83]
Why Invariant Violation：Invariant Violation：requireNativeComponent：“wheelPicker” was not found in the UIManager。

rn：0.57.0

thanks！

**Comment by tphuc012** [comment]
use react-native link react-native-wheel-picker-android
It work to me

**Comment by KenPanda** [comment]
3q

**Comment by KenPanda** [comment]
3Qs

**Comment by Kaygi22** [comment]
I had the same issue, but I came to link it manually:

add the following lines into their specific files: 

**settings.gradle** : 
> **path**: gradle/setting.gradel
include ':react-native-wheel-picker-android'
project(':react-native-wheel-picker-android').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-wheel-picker-android/android')

**build.gradle** : 
> **path**: app/build.gradel
 implementation project(':react-native-wheel-picker-android')


**MainApplication.java** : 
> **path**: app/src/main/java/MainApplication.java
in your  List<ReactPackage> getPackages() method, add the following line just after new MainReactPackage(): new WheelPickerPackage()
so your method should look like this: 

`@Override
    protected List<ReactPackage> getPackages() {
      // Returning the Packages this way is better than calling the getPackages that was here
      //by default which overridden my FbModule
      return new ArrayList<>(Arrays.<ReactPackage>asList(
              new MainReactPackage(),
              new WheelPickerPackage()
      ));
    }`

and then it should work

**Comment by hpelitebook745G2** [comment]
@Kaygi22 in MainApplication.java, how do you import it?

**Comment by smlarkin** [comment]
I am using Expo.io to develop.  I am also getting this error:

"Invariant Violation: requireNativeComponent: "WheelPicker" was not found in the UIManager."

Does anyone have any suggestions for how to fix this in the Expo environment?

**Comment by ArtemKosiakevych** [comment]
Please read the expo [docs](https://docs.expo.io/versions/latest/introduction/faq/)
You can't use custom native code

**Comment by wangtiger317** [comment]
I have same issue and is using the react native version 0.634
