### ISSUE TITLE
onItemSelected is triggered onload (only on android device)

### ISSUE THREAD

**Issue by js-jegan** [kalontech/ReactNativeWheelPicker#87]
On Load, `onItemSelected` is triggered with selected position as `0`. Is there a way to stop this. I strongly recommend to have this solved.

Because of this issue, only without default selected index the picker works.

**Comment by jeffmeoi** [comment]
I meet the problem too.

**Comment by Makar8000** [comment]
Experiencing the same issue on RN v0.59.4

**Comment by amallo** [comment]
+1

**Comment by madandrija** [comment]
Duplicate of https://github.com/KalonTech/ReactNativeWheelPicker/issues/87

**Comment by ArtemKosiakevych** [comment]
try to use `initPosition`
