### ISSUE TITLE
TimePicker is not cyclic (ios)

### ISSUE THREAD

**Issue by arelstone** [kalontech/ReactNativeWheelPicker#92]
I've experienced that the TimePicker for IOS is not cyclic. This works fine for Android. 

Did i oversee something?

**iOS screenshot**
<img width="290" alt="Screen Shot 2019-06-24 at 08 54 28" src="https://user-images.githubusercontent.com/1322047/59997594-be479d00-965d-11e9-918d-683f34dfb7be.png">

**Android screenshot**
![Screenshot_1561359262](https://user-images.githubusercontent.com/1322047/59997623-d0294000-965d-11e9-8656-0af5f372204c.png)

**Code**
```tsx
import React from 'react';
import { HoursAndMinutes } from '../interfaces/Calendar';
import { TimePicker } from 'react-native-wheel-picker-android'

interface Props {
    onChange: ({ hours, minutes }: HoursAndMinutes) => void;
    initialValue?: any;
    minuteInterval?: string[];
    hourInterval?: string[];
}

interface State {
    initialDate: any;
}

export default class Timepicker extends React.Component<Props, State> {

    static defaultProps = {
        minuteInterval: ['00', '15', '30', '45'],

    };

    state: State = {
        initialDate: null,
    };

    componentWillMount() {
        const { initialValue }: Props = this.props;
        const { initialDate }: State = this.state;


        this.setState({
            initialDate: initialValue && (initialDate !== initialValue) ? new Date(initialValue) : new Date(),
        });
    }

    render() {
        const { minuteInterval, hourInterval }: Props = this.props;
        const { initialDate }: State = this.state;

        return <TimePicker
            isCyclic
            format24
            hideDate={true}
            initDate={initialDate}
            minutes={minuteInterval}
            hours={hourInterval}
            onTimeSelected={this.handleOnChange}
        />;
    }

    handleOnChange = (date: Date) => {
        const { onChange }: Props = this.props;
        this.setState({ initialDate: date });

        onChange({
            hours: new Date(date).getHours(),
            minutes: new Date(date).getMinutes(),
        });
    }
}

```

**Comment by erikvdplas** [comment]
Also stumbled upon this problem, any updates? @arelstone

**Comment by arelstone** [comment]
@erikvdplas  I didn't find a solution to this.
I ended up using a different package for Android and using the native one for IOS

**Comment by erikvdplas** [comment]
Thanks for your reply! For me, the wheel being cyclic wasn’t quite a necessity, and due to time constraints I’ll just stick with this package for now... hoping it will be fixed at some point.

**Comment by ArtemKosiakevych** [comment]
On IOs [Native picker](https://reactnative.dev/docs/picker) is using and native picker doesn't support cyclic, If I replace TImePicker with native IOs one then all props available now in TimePicker won't work
You can use TImePicker for android and native Picker for IOs if you need cyclic and don't need custom hours and minutes
