### ISSUE TITLE
how to detect if the wheel picker is scrolling?

### ISSUE THREAD

**Issue by hweister** [kalontech/ReactNativeWheelPicker#95]

**Comment by jawwad22** [comment]
Hi, Well you cant detect scrolling of wheelpicker, but there is a way you can,

put your wheelpicker inside TouchableWithoutFeedback, 
apply onPress on TWFeedback, which will change state of "wheelpickerScroll" to true
In wheelpicker funtion itemSelect, make your wheelpickerScroll back to false,

in this way you can find wheelpicker scrolling or not...
