### ISSUE TITLE
picker width

### ISSUE THREAD

**Issue by kingofday** [kalontech/ReactNativeWheelPicker#96]
how can make picker box smaller, i want to have three picker in one row like date picker but for persian?
but now it not follow width of it's wrapper view:{flex:0.2}

**Comment by alexandre033** [comment]
You need to specify width and height.
`style={{width: 100, height: 100}}`

**Comment by nishantsri2** [comment]
### How can i limit height/ Wheel radius of Wheelpicker?
Is there any way to limit number of items displaying at a time, so i can reduce height?

**Comment by yacineblr** [comment]
Did you find a solution?

**Comment by kingofday** [comment]
no i used my own component

**Comment by lennartwollatz** [comment]
An Auto resize would be nice for default. 
Change 
`static defaultProps = {
    style: {
      width: 200,
      height: 150,
    },
  }`
To:
`static defaultProps = {
    style: {
      width: "auto",
      height: 150,
    },
  }`
In 
- src\WheelPicker.ios.js 
- src\WheelPicker.android.js

Then the Component will resize automatic. If you would like to have a static width you can set this by the componentWrapper.

**Comment by ArtemKosiakevych** [comment]
You can set picker width with style prop
