### ISSUE TITLE
Android: Selected position bounces off

### ISSUE THREAD

**Issue by AsminBudha** [kalontech/ReactNativeWheelPicker#97]
Currently, I am using this library in android. And, I have found some unusual behavior. When we press on picker first time it's working fine but after scroll when we press it bounces off.

Steps to reproduce:
1. Scroll up or down ( Suppose, initially we're in 0th position then we scroll to 2nd position).
2. Now when we touch or press the picker. It bounces off by 2 i.e from 2 we're directly jumped to 4.

**Comment by hweister** [comment]
I guess you use "selectedItem" to set the init value, try "initPosition" instead.

**Comment by AsminBudha** [comment]
> I guess you use "selectedItem" to set the init value, try "initPosition" instead.

I have used initPosition. Here is my component:
`<WheelPicker
          isCyclic={true}
          itemTextSize={20}
          selectedItemTextSize={20}
          hideIndicator={true}
          data={title.toLowerCase() === 'hour' ? getTimeHour() : getTimeMinute()}
          initPosition={this.state[title.toLowerCase()]}
          onItemSelected={selectedItem => this.onItemSelected(selectedItem, title.toLowerCase())}
        />`

**Comment by ArtemKosiakevych** [comment]
Init position can't be depended on state, use the initial position as constant and if you want to change selected item programmatically use selectedItem prop.
For your case just remove `initPosition` param
